package com.spectralint.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.spectralint.model.AgentResult;
import com.spectralint.model.AnalysisReport;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
public class ReportExportService {

    private final ObjectMapper objectMapper = new ObjectMapper();

    public String exportAsText(AnalysisReport report) {
        StringBuilder sb = new StringBuilder();
        String line = "═".repeat(70);
        String dash = "─".repeat(70);

        sb.append(line).append("\n");
        sb.append("       SPECTRALINT — INTELLIGENCE & SECURITY REPORT\n");
        sb.append(line).append("\n");
        sb.append(String.format("Target    : %s%n", report.getUrl()));
        sb.append(String.format("Domain    : %s%n", report.getDomain()));
        sb.append(String.format("Mode      : %s%n", report.getMode().toUpperCase()));
        sb.append(String.format("Status    : %s%n", report.getStatus()));
        sb.append(String.format("Duration  : %dms%n", report.getTotalDurationMs()));
        sb.append(String.format("Generated : %s%n", report.getCompletedAt()));
        sb.append(dash).append("\n\n");

        Map<String, Object> compiled = report.getCompiledReport();
        if (compiled != null) {
            appendSection(sb, "EXECUTIVE SUMMARY", compiled.get("executive_summary"));
            appendSection(sb, "RISK SCORE", compiled.get("risk_score") + "/100 — " + compiled.get("security_posture"));
            appendSection(sb, "RISK JUSTIFICATION", compiled.get("risk_justification"));
            appendListSection(sb, "CRITICAL FINDINGS", compiled.get("critical_findings"));
            appendListSection(sb, "RECOMMENDATIONS", compiled.get("recommendations"));
            appendSection(sb, "COMPLIANCE GAPS", compiled.get("compliance_gaps"));
            appendListSection(sb, "NEXT STEPS", compiled.get("next_steps"));
            sb.append(dash).append("\n\n");
        }

        sb.append("AGENT INTELLIGENCE DATA\n").append(dash).append("\n");
        List<AgentResult> results = report.getAgentResults();
        if (results != null) {
            for (AgentResult ar : results) {
                sb.append(String.format("%n[%s] — %s (%dms)%n",
                    ar.getAgentId().toUpperCase(), ar.getStatus(), ar.getDurationMs()));
                if (ar.getData() != null) {
                    try {
                        sb.append(objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(ar.getData()));
                    } catch (Exception e) {
                        sb.append(ar.getData().toString());
                    }
                } else if (ar.getErrorMessage() != null) {
                    sb.append("ERROR: ").append(ar.getErrorMessage());
                }
                sb.append("\n");
            }
        }

        sb.append("\n").append(line).append("\n");
        sb.append("END OF REPORT — Generated by SpectralINT\n");
        sb.append(line).append("\n");
        return sb.toString();
    }

    public String exportAsJson(AnalysisReport report) {
        try {
            return objectMapper.writerWithDefaultPrettyPrinter().writeValueAsString(report);
        } catch (Exception e) {
            return "{\"error\": \"Failed to serialize report\"}";
        }
    }

    @SuppressWarnings("unchecked")
    private void appendListSection(StringBuilder sb, String title, Object value) {
        if (value == null) return;
        sb.append(title).append("\n");
        if (value instanceof List) {
            int i = 1;
            for (Object item : (List<?>) value) {
                sb.append(String.format("  %d. %s%n", i++, item));
            }
        } else {
            sb.append("  ").append(value).append("\n");
        }
        sb.append("\n");
    }

    private void appendSection(StringBuilder sb, String title, Object value) {
        if (value == null) return;
        sb.append(title).append("\n");
        sb.append(value).append("\n\n");
    }
}
